### PR TITLE
Adding source table name and column name mapping for Glue handlers

### PR DESCRIPTION
**Pull request by atennak1**
*Issue #, if available:* https://github.com/awslabs/aws-athena-query-federation/issues/78

*Description of changes:* Adding source table name and column name mapping for Glue handlers.  Data sources such as DynamoDB allow more characters and upper case in table names while Glue does not, meaning that it may not be possible for customers to make a Glue table with the same exact name
as their data source's table.  This allows customers to add a table property in Glue with the source table name.  This can also extract the source table name from an ARN populated in the Glue table's 
StorageDescriptor.Location property (Glue crawlers populate this).  It also enables a table property for column mapping.

I adapted the Dynamo connector to use this.  The other connectors expose table names directly from the source (DocDB and HBase) or don't have sources tables (Redis).

*Testing*: Unit tests and empirical testing with an uploaded Dynamo connector and a crawled table with different name than the source.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by avirtuos** [comment]
Maybe we should add this to the GlueMetadataHander instead so that all
connectors that use Glue can use a table property to override the
tablename?

**Comment by atennak1** [comment]
@avirtuos I did :) Sorry if the description was misleading

**Comment by avirtuos** [comment]
Ugh, I can't read lately. :)

**Comment by houmark** [comment]
@atennak1 This looks like something I should be testing :)

I'll try merging this fix with the other fix I am already testing, and provide feedback.

Thank you!

**Comment by atennak1** [comment]
Yes please do. Thanks @houmark !

**Comment by houmark** [comment]
I had a chance to test this last night. I did a merge of this branch into the existing fix I had for the empty structs, so this test was based on both of these in once.

While I no longer get errors, there's something going on with selecting from some fields in the glue based table. I have some sensible columns called `firstname` and `lastname`, and those columns return empty on any query. This seems to affect most of my columns, but not all. I tried sorting on a string/date column, which normally works, but it also seems to return the correct result.

In addition I did a `count(*) as total` with a `GROUP BY` and that returned zero rows, while the non-glue based table works perfectly.

When the 404 error was gone, I was sure it would just work, as to my understanding, the glue connector/mapping, is just a mapping, but for some reason things go terribly wrong.

Just to make sure, I did a re-crawl with my existing crawler, but the results were the same. Checking the schema, the fields exist and are strings in the mapping (they show up as varchars in Athena).

Since I'm getting no errors on this one, but just empty columns, I'm unsure on how to proceed here. Anything you need, let me know.

**Comment by atennak1** [comment]
Thanks for testing @houmark ! Does the casing of the columns in Glue match
DynamoDB? I noticed that glue does not allow capital letters in column
names. If the casing does not match then the connector currently assumes
that there is no data for that column. If this is the case for you I'm
thinking we may need to add some capability for case insensitive
matching/mapping.

**Comment by houmark** [comment]
@atennak1 Yes, that makes total sense. My columns/fields in DynamoDB are `camelCase` and when using Glue they are lowercased in the Schema, and shows up in the column list as lowercased, but data can't be fetched in a query. I just tested now, and the columns that has only lowercase in DynamoDB are working correctly and fetches data, while the camelCased ones return nothing but also doesn't give any error.

With the interference schema it will show the column names camelCased but it does not really seem to care if I use lowercase or camelcase in the query.

**Comment by atennak1** [comment]
@houmark I've pushed a commit to handle the column problem as well.  Give it another try.  This will require you to add a table property called `columnMapping` that looks like `mycolumna=myColumnA,mycolumnb=myColumnB`. This seemed like the best way to handle this without hurting performance.

**Comment by houmark** [comment]
Thanks for the quick update. I've tested the column mapping, and had half success half failure.

I mapped some of the camelCased fields, some were string/varchar and seems to work, but I also have some bigint fields which I also mapped, but I now get an error when trying to query those fields. They are in the columns/fields list in both Glue and Athena and it seems to be happening specifically to all bigint fields. It also doesn't matter if the field is queried all lowercase or camelCased:

```
Your query has the following error(s):

GENERIC_USER_ERROR: Encountered an exception[java.lang.RuntimeException] from your LambdaFunction[arn:aws:lambda:us-east-1:ano:function:myfunction] executed in context[S3SpillLocation{bucket='my-athena-spill', key='athena-spill/d928cd63-dd3f-4a21-9574-ano/ano-cea6-41e7-a57d-ano', directory=true}] with message[Error while processing field totalRevenue]

This query ran against the "default" database, unless qualified by the query. Please post the error message on our forum or contact customer support with Query Id: d928cd63-dd3f-4a21-9574-c01612726202.
```

So close :)

**Comment by atennak1** [comment]
Ah that looks related to https://github.com/awslabs/aws-athena-query-federation/issues/81 . I don't expect it to be a difficult fix but for now you can get around it by making those columns `decimal` in Glue.

**Comment by atennak1** [comment]
@houmark it was easy enough so I pushed a quick commit for the bigint problem.  But it will only handle top-level bigints (not nested in arrays or structs).

**Comment by houmark** [comment]
Brilliant! That works! I'm still testing all fields, but it seems like this maps everything out correctly.

Not really related, but it may actually be best for me to change those fields to decimal, because I have money values saved as cents, with the purpose of dividing by 100. When doing that with the interference schema, I get a decimal and the correct decimals. When it's a `bigint`, I lose the decimals and I'll probably have to `CAST` to decimal to keep them anyways, so I'm considering what's the best option.

**Comment by avirtuos** [comment]
@atennak1 Can you take a look at the merge conflicts? I've approved the changes so you can resolve conflicts and merge at your discretion.

**Pull request merged**
