### PR TITLE
Upgrading to Log4j 2 to address Log4j vulnerability

### PR DESCRIPTION
**Pull request by atennak1**
*Issue #, if available:* https://github.com/awslabs/aws-athena-query-federation/issues/89

*Description of changes:* Upgrading to Log4j 2.13.0 to address vulnerability.

*Testing*: mvn dependency:tree no longer shows Log4j 1.x.  Deployed and tested DDB connector and verified no regression.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by avirtuos** [comment]
Did we test this by running tests for all connectors, the ask, Athena, and @seth's stuff? I vaguely recall log4j2 caused issues for something. Why not just bump to the newer log4j 1?  

Alternatively we could change our pom so that only connectors have this dependency and not the ask itself.

**Comment by atennak1** [comment]
It's my understanding that this vulnerability is not addressed in log4j v1.

I was also concerned that transitive dependencies may rely on log4j v1 APIs but I took a look at the existing dependency tree before modifications and luckily for us all of them used JCL or Slf4j.

I suppose it's possible that future connectors may have the log4j v1 dependency, in which case I believe they may be able to bridge to Slf4j or log4j v2.

In any case I do think pushing down the log4j v2 dependencies down to the connectors and out of the SDK is the right move for cleanliness anyway so I will make that change.

**Comment by avirtuos** [comment]
approved, feel free to merge and test when you are ready.

**Comment by atennak1** [comment]
Tested all connectors by deploying them and running validator script and actual queries.

**Pull request merged**
