### PR TITLE
env variable log level for athena-federation-sdk

### PR DESCRIPTION
**Pull request by ahuwaa**
*Description of changes:*
This is a suggestion on providing more control over logging. In its current state, the athena-federation-sdk uses log level `INFO` to log full requests e.g.
https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/MetadataHandler.java#L232
https://github.com/awslabs/aws-athena-query-federation/blob/master/athena-federation-sdk/src/main/java/com/amazonaws/athena/connector/lambda/handlers/RecordHandler.java#L154
This includes potentially sensitive information if stored within Split metadata or records written back to Athena after `READ_RECORDS`. It can also be incredibly verbose if there is a lot of data being processed. While this defaults to `INFO`, an env variable can be specified during runtime to limit logging to `warn` or up to not expose the sensitive info e.g. `ATHENA_FEDERATION_SDK_LOG_LEVEL=warn`

For custom connectors, the log4j2 conf can be modified appropriately but for existing connectors deployed from SAM, this provides a bit more control.

*Testing:*
* Compared results from `AWS_REGION=us-west-2 mvn test` and `AWS_REGION=us-west-2 ATHENA_FEDERATION_SDK_LOG_LEVEL=ERROR mvn test` within `athena-aws-cmdb`. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by atennak1** [comment]
This is great! Can you update the description with what testing you did?

**Review by avirtuos — APPROVED** [review]
looks good.

**Comment by avirtuos** [comment]
@burhan94 can you test and merge this? I think we want this rolled out with a default of 'WARN' log level so you might need to tweak the PR before merging. I also think you want to expedite this to happen before the upcoming GA.

**Comment by ahuwaa** [comment]
Testing info added

**Comment by ahuwaa** [comment]
Note also this env control only applies to the `athena-federation-sdk` package. Assuming this code is also what is used for SAM deployments, I was thinking if this approach moves forward then it may also make sense to add another env variable for the custom connector log level itself.

**Comment by burhan94** [comment]
sent updated commit with default level as warn. Confirmed in testing that only WARN log statements show up from the federation SDK.

**Review by atennak1 — APPROVED** [review]

**Pull request merged**
