### PR TITLE
#373 DynamoDB range of key needs BETWEEN syntax

### PR DESCRIPTION
**Pull request by laurihak**
*Issue #, if available:*
#373

*Description of changes:*
generateSingleColumnFilter -> rangeConjucts 
Changed the way sort key range is written to dynamodb request.
DynamoDB needs BETWEEN clause to not get error 

I also had to to change the test to fit the correct syntax

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

AWS DOCS:

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.KeyConditions.html

Screen Shot 2021-03-24 at 19 30 54

### CODE REVIEW

**Review by atennak1 — COMMENTED** [review]
Thanks for the PR! But I don't think this fixes the case where the start and/or end of the range is exclusive, e.g. `1 <= x < 10`.  Since BETWEEN is always inclusive I think we'll have to use BETWEEN but then somehow remove 1 or 2 bookend records once they're returned from DDB.  That's going to be kind of ugly but I don't see another way.

**Comment by laurihak** [comment]
Yes, i think dynamodb does not support exlusive sorting with range of key. Removing records after the request will be kind of a hassle, but I agree it is the only way, if it really needs to be supported.

**Comment by avirtuos** [comment]
Hey @atennak1 if you have a sec, whats your take on the current state of this. Should we abandon or whats needed to move forward?

**Comment by atennak1** [comment]
@avirtuos @laurihak thought about it again and I think this PR will work as-is.  The connector will return an extra record or two, but Athena should still enforce the predicates on the returned data, so query results should still be correct.  Would be good to validate this with some test queries on a ranged dataset.

**Comment by henrymai** [comment]
@laurihak

Thank you for your contribution.
We are going to merge a safer version of this patch that only handles the fully inclusive range situation here: https://github.com/awslabs/aws-athena-query-federation/pull/787

**Pull request closed without merging**
