### PR TITLE
Add a Deltalake connector

### PR DESCRIPTION
**Pull request by malonsocasas**
*Issue #310 :*

*Description of changes:*
Add a first version of a Deltalake connector (https://github.com/delta-io/delta) so that Athena can interpret table schemas/partitions automatically (some current limitations are listed in the README).

Note that my first attempt was to use: https://github.com/delta-io/connectors. However, the library being in Scala and depending on a lot of packages, it makes it unsuitable for a Lambda code (with a limitation of 250 MB).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by slomkarafa** [comment]
wazzup guys :D
@malonsocasas @avirtuos  any updates on this topic?
Thanks

**Comment by artloder** [comment]
Hey @avirtuos I'm following along as well to see if this PR can be merged; it's listed on https://delta.io/integrations as a "preview"  release but it would be great if this were an official part of _awslabs/aws-athena-query-federation_.

**Comment by slomkarafa** [comment]
Hello, is any one working on this topic? Because I am and I do not want to duplicate with someone ;)

**Comment by slomkarafa** [comment]
Hello, hello its me again, as this PR is stale I have created new one #825  which is an extension for that one :p cheers

**Comment by henrymai** [comment]
See: https://github.com/awslabs/aws-athena-query-federation/pull/825#issuecomment-1359839427

**Pull request closed without merging**
