### PR TITLE
[BUG] Querying bigquery from multiple projects with one service account

### PR DESCRIPTION
**Pull request by jason-pixl**
*Issue #, if available:*https://github.com/awslabs/aws-athena-query-federation/issues/845

*Description of changes:*https://github.com/awslabs/aws-athena-query-federation/issues/845#issuecomment-1338826803

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by henrymai** [comment]
Hi @jason-pixl 

Thank you for looking into this and working on this.

You are on the right trail here in regards to setting the `projectId` on the BigQuery client, because I do notice that we don't set the `projectId` anywhere in `BigQueryRecordHandler::readWithConstraint` whereas we do at least set it as part of the api invocations in the `BigQueryMetadataHandler` (where the issue author actually does mention they were able to retrieve project B's datasets, tables, etc correctly).

However, the environment variable is intended to be an override, where typically the `projectId` is instead derived from the Athena SQL query, which provides the user much more flexibility than having to set the environment variable each time before they make a query.

So instead of doing that, we should actually be setting the `projectId` on the BigQuery client after the code calls `BigQueryUtils.getProjectName()` (which does make use of the environment variable override if set, but if not, just gets the `projectId` from the Athena SQL query by default).

For reference see the code base for usages and the definition of:
```BigQueryUtils.getProjectName(listTablesRequest);```

In order to do what I mention above, we would need to refactor the code so that it doesn't just construct the BigQueryClient immediately in the constructor of (at least) the BigQueryRecordHandler.

I will push an update to your pull request with the refactor to show you what I mean.

**Comment by jason-pixl** [comment]
> Hi @jason-pixl
> 
> Thank you for looking into this and working on this.
> 
> You are on the right trail here in regards to setting the `projectId` on the BigQuery client, because I do notice that we don't set the `projectId` anywhere in `BigQueryRecordHandler::readWithConstraint` whereas we do at least set it as part of the api invocations in the `BigQueryMetadataHandler` (where the issue author actually does mention they were able to retrieve project B's datasets, tables, etc correctly).
> 
> However, the environment variable is intended to be an override, where typically the `projectId` is instead derived from the Athena SQL query, which provides the user much more flexibility than having to set the environment variable each time before they make a query.
> 
> So instead of doing that, we should actually be setting the `projectId` on the BigQuery client after the code calls `BigQueryUtils.getProjectName()` (which does make use of the environment variable override if set, but if not, just gets the `projectId` from the Athena SQL query by default).
> 
> For reference see the code base for usages and the definition of: `BigQueryUtils.getProjectName(listTablesRequest);`
> 
> In order to do what I mention above, we would need to refactor the code so that it doesn't just construct the BigQueryClient immediately in the constructor of (at least) the BigQueryRecordHandler.
> 
> I will push an update to your pull request with the refactor to show you what I mean.

In the beginning, I studied how QueryJobConfiguration sets projectId, but unfortunately, although google-cloud-bigquery provides it, it is a private method that is not exposed to the outside world, but when executing SQL statements, they will go to bigQueryClient Read the corresponding projectId, if you refactor, this may help you

**Comment by henrymai** [comment]
Right, the idea is to set it on the Builder before creating the client. Which is why we need to refactor the code so that we can do so. I will have my patch up shortly.

**Comment by henrymai** [comment]
I didn't have permissions to push to your fork and branch, so I had to create a new pull request with my changes.

Here it is: https://github.com/awslabs/aws-athena-query-federation/pull/863/files

Took me longer than expected because of dealing with the tests and PowerMockito.

**Pull request closed without merging**
