### PR TITLE
Add ssl support for Redis Connector

### PR DESCRIPTION
**Pull request by burhan94**
Currently the redis connector does not support encrypted redis clusters. This change will allow users to add a rediss:// prefix to their hostname to allow ssl access.

### CODE REVIEW

**Comment by burhan94** [comment]
Closing since customer also requires multi-cluster support. Need to look into other support options, and will include SSL support with multi-cluster support.

**Comment by TejjeT** [comment]
@burhan94 any ETA on this ? Just want to make sure I am not duplicating the effort on writing something similar.

**Comment by burhan94** [comment]
Hey, I ended up closing the PR since I'm not sure if Jedis is the right tool for this. I'm weighing my options for using Jedis vs Lettuce for our redis client, so adding SSL support this way could make it difficult if we decide to switch to Lettuce in terms of backwards compatibility. Unfortunately we had to re-prioritize, so it might be some time before we can get back to this since we're already spread pretty thin.

**Comment by mannharleen** [comment]
Why has the issues been closed?

**Pull request closed without merging**
