### PR TITLE
Add Deltalake connector with complex types

### PR DESCRIPTION
**Pull request by slomkarafa**
*Issue #310  :*

Add a first version of a Deltalake connector (https://github.com/delta-io/delta) so that Athena can interpret table schemas/partitions automatically (some current limitations are listed in the README).
This PR is an extension of [@malonsocasasa](https://github.com/malonsocasas) work in #509 PR. I have:
 - added support for complex types like arrays, maps, structs and their nested options,
 - alligned code with checkstyle requirements,
 - upgraded to newest aws-athena-query-federation version

After those changes you are able to query nested complex types via AWS Athena from deltalake data source. Tests showed that all kinds of complexity are supported.
Unfortunately when using athena-deltalake lambda for query federation in AWS Athena, Maps nested inside other complex types(e.g. Map<string, Map>) are showed as empty. I don't know if thats a bug on my side or maybe there is some Athena limitation? @henrymai @shivachinnam @ykrystal @kparwal @burhan94 does anyone know the answer? Thanks in advance

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pabloFloresHdz** [comment]
Hi @slomkarafa! Thanks for following up the work with the connector! 
Sorry for posting this here, but I couldn't find a more suitable place to ask for troubleshooting. I installed the connector and everything seemed to be working fine after setting it up. Athena detected the connector(datasource), the database, the tables and the table's schema. Nevertheless, when trying to actually run queries Athena throws a `table not found` error. I discarded problems with the db and table names by lowercasing and removing dashes from them. I also lowercased all the table's columns. I also removed all complex types, my table contains only strings and dates. I also removed all partitions but the `date` partition from my table but still no luck. 
I was hoping you could point me in the right direction to successfully setting up the connector
BTW the data is in a bucket like `s3://athena-delta-connector/exampledb/exampletb` I'm not sure if the dashes in the bucket name may be affecting in some way
Again, thanks for the awesome work and hope you can help me please!
An example of what I'm getting and how I'm querying can be seen in the image
Screen Shot 2022-12-07 at 11 01 48

**Comment by slomkarafa** [comment]
Hello @pabloFloresHdz ,
I confirm that trying to use this lambda as data source in Athena doesn't work for me too :( Looks like Athena issue, but I haven't dive into it. If you need to use Athena Data Source, I strongly encourage you to investigate it deeper and contribute ;)
There is a workaround and also the way how I use this lambda. You can invoke it from sql, like:

`select * from "lambda:<your-lambda-name>"."exampledb"."exampletb"`

I hope I helped a little bit : p
cheers

**Comment by burhan94** [comment]
Hi, just wanted to let you know that we've added native delta like support. We really appreciate the effort here though, and if you have any other connector ideas, we would love to hear them :)

https://aws.amazon.com/blogs/big-data/introducing-native-delta-lake-table-support-with-aws-glue-crawlers/

**Comment by slomkarafa** [comment]
Hello,
Thanks @burhan94 for info. Works like a charm! :D

As my PR has no more sense, I am closing it

**Pull request closed without merging**
